version: "3.8"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/app
      - ./docker/development/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
      - storage

  php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
      - storage

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mtz_usr
      POSTGRES_PASSWORD: mtz_pass
      POSTGRES_DB: mtz_db
    volumes:
      - mtz-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    entrypoint: sh -c 'mkdir -p /data/mtz && docker-entrypoint.sh minio server /data --console-address ":9001"'
    volumes:
      - mtz-storage:/data
    environment:
      MINIO_ROOT_USER: s3_mtz_usr
      MINIO_ROOT_PASSWORD: s3_mtz_pass
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  mtz-postgres:
  mtz-storage: