version: "3.8"
services:
  backend-nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/app
      - ./docker/development/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend-php-fpm

  backend-php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
    links:
      - mailer

  backend-php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
    links:
      - mailer

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mtz_usr
      POSTGRES_PASSWORD: mtz_pass
      POSTGRES_DB: mtz_db
    volumes:
      - mtz-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mtz-postgres: